/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import businesslogic.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import models.*;
import staticfiles.ColorScheme;
import staticfiles.DataResultStatus;
import staticfiles.RegexPattern;

/**
 *
 * @author tron
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    
    private boolean formDirty = false;
    UserModelRepository _userModelRepository = new UserModelRepository();
    
    public RegisterForm() {
        initComponents();
        setComponents();
        setColorScheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        lblRegister = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRetypePwd = new javax.swing.JLabel();
        txtRetypePwd = new javax.swing.JPasswordField();
        btnClear = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblLoginAcct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        topPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblRegister.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("REGISTER");

        lblMinimize.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });

        lblExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblExit)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblExit)
                        .addComponent(lblMinimize))
                    .addComponent(lblRegister))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        bottomPanel.setBackground(new java.awt.Color(255, 0, 51));

        lblFirstName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFirstName.setText("First Name:");

        txtFirstName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtFirstName.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        txtFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFirstNameFocusLost(evt);
            }
        });

        lblLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblLastName.setText("Last Name:");

        txtLastName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLastNameFocusLost(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblUserName.setText("Username:");

        txtUserName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserNameFocusLost(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        txtPassword.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        lblRetypePwd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblRetypePwd.setText("Retype Pwd:");

        txtRetypePwd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRetypePwd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRetypePwdFocusLost(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnRegister.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblLoginAcct.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblLoginAcct.setText("Click here to login to your account if you already have one.");
        lblLoginAcct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoginAcct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginAcctMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLoginAcctMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLoginAcctMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblUserName)
                            .addComponent(lblRetypePwd))
                        .addGap(18, 18, 18)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassword)
                            .addComponent(txtUserName)
                            .addComponent(txtRetypePwd)))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottomPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFirstName)
                                    .addComponent(lblLastName)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEmail)))
                        .addGap(18, 18, 18)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                        .addComponent(lblLoginAcct)
                        .addGap(46, 46, 46))))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRetypePwd)
                    .addComponent(txtRetypePwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLoginAcct, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottomPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setForeground(ColorScheme.secondaryColor);
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setForeground(ColorScheme.quaternaryColor);
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        lblExit.setForeground(ColorScheme.secondaryColor);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        lblExit.setForeground(ColorScheme.quaternaryColor);
    }//GEN-LAST:event_lblExitMouseExited

    private void lblLoginAcctMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginAcctMouseEntered
        lblLoginAcct.setForeground(ColorScheme.primaryColor);
    }//GEN-LAST:event_lblLoginAcctMouseEntered

    private void lblLoginAcctMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginAcctMouseExited
        lblLoginAcct.setForeground(ColorScheme.quaternaryColor);
    }//GEN-LAST:event_lblLoginAcctMouseExited

    private void lblLoginAcctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginAcctMouseClicked
        //if there is any input on the form prompt the user for confimation
        boolean confirmed = true;
        if(!txtFirstName.getText().equals("") || !txtLastName.getText().equals("") ||!txtEmail.getText().equals("") ||
                !txtUserName.getText().equals("") || !txtPassword.getText().equals("") || !txtRetypePwd.getText().equals("")){
            int confirmExit = JOptionPane.showOptionDialog(null, "All Choices will be lost.\n"
                + "Are you sure you want to return to the Login form?", "Return to Login",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, null, null);
            
            confirmed = confirmExit == JOptionPane.YES_OPTION;
        }
        
        if(confirmed){
            this.setVisible(false);
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_lblLoginAcctMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        formDirty = true;
        DataResult result = new DataResult();
        if(!formValid()){
            JOptionPane.showOptionDialog(null, "Please fix the highlighted error", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        } else if(!passwordMatch()){
            JOptionPane.showOptionDialog(null, "Password Mismatch", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        } else if(!validEmail()){
            JOptionPane.showOptionDialog(null, "Invalid Email Format", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        } else if (userNameExist()){
            JOptionPane.showOptionDialog(null, "Username already exists", "Error",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, null, null);
        }
        else{
            UserModel model = new UserModel(txtFirstName.getText().trim(), txtLastName.getText().trim(), 
                    txtEmail.getText().trim(), txtUserName.getText().trim(), txtPassword.getText().trim());
            result = _userModelRepository.RegisterUser(model);
            
            if(result.StatusCode == DataResultStatus.CREATED_STATUS){
                JOptionPane.showOptionDialog(null, "Registration Successful. New account created!!", "Success",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                this.setVisible(false);
                new LoginForm().setVisible(true);
                
            } else{
                JOptionPane.showOptionDialog(null, "Registration failure: " + result.Message, "Failure",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, null, null);
            }
            
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFirstName.setText("");
        txtLastName.setText("");
        txtEmail.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtRetypePwd.setText("");
        
        txtFirstName.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFirstNameFocusLost
        if(formDirty && !txtFirstName.getText().equals("")){
            txtFirstName.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtFirstNameFocusLost

    private void txtLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLastNameFocusLost
        if(formDirty && !txtLastName.getText().equals("")){
            txtLastName.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtLastNameFocusLost

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(formDirty && !txtEmail.getText().equals("")){
            txtEmail.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtUserNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusLost
        if(formDirty && !txtUserName.getText().equals("")){
            txtUserName.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtUserNameFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        if(formDirty && !txtPassword.getText().equals("")){
            txtPassword.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtRetypePwdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRetypePwdFocusLost
        if(formDirty && !txtRetypePwd.getText().equals("")){
            txtRetypePwd.setBorder(new LineBorder(ColorScheme.errorColor, 0));
        }
    }//GEN-LAST:event_txtRetypePwdFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }
    
    public boolean formValid(){
        boolean valid = true;
        if (txtFirstName.getText().equals("")){
            txtFirstName.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
        if (txtLastName.getText().equals("")){
            txtLastName.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
        if (txtEmail.getText().equals("")){
            txtEmail.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
        if (txtUserName.getText().equals("")){
            txtUserName.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
        if (txtPassword.getText().equals("")){
            txtPassword.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
        if (txtRetypePwd.getText().equals("")){
            txtRetypePwd.setBorder(new LineBorder(ColorScheme.errorColor, 2));
            valid = false;
        }
            
        
        return valid;
    }
    
    public boolean passwordMatch(){
        return txtPassword.getText().equals(txtRetypePwd.getText());
    }
    
    public boolean validEmail(){
        Matcher matcher = RegexPattern.VALID_EMAIL_ADDRESS_REGEX.matcher(txtEmail.getText());
        
        return matcher.find();
    }
    
    public boolean userNameExist(){
        DataResult dataResult = _userModelRepository.CheckForUsername(txtUserName.getText().trim());
        
        //return true if name already exists
        return dataResult.Data != null;
    }
    
    private void setComponents(){
        //lblErrors.setVisible(false);
    }
    
    private void setColorScheme(){
        topPanel.setBackground(ColorScheme.primaryColor);
        bottomPanel.setBackground(ColorScheme.secondaryColor);
        
        lblRegister.setForeground(ColorScheme.quaternaryColor);
        lblExit.setForeground(ColorScheme.quaternaryColor);
        lblMinimize.setForeground(ColorScheme.quaternaryColor);
        lblFirstName.setForeground(ColorScheme.quaternaryColor);
        lblLastName.setForeground(ColorScheme.quaternaryColor);
        lblEmail.setForeground(ColorScheme.quaternaryColor);
        lblUserName.setForeground(ColorScheme.quaternaryColor);
        lblPassword.setForeground(ColorScheme.quaternaryColor);
        lblRetypePwd.setForeground(ColorScheme.quaternaryColor);
        //lblErrors.setForeground(ColorScheme.errorColor);
        
        btnClear.setBackground(ColorScheme.tertiaryColor);
        btnClear.setForeground(ColorScheme.quaternaryColor);
        
        btnRegister.setBackground(ColorScheme.tertiaryColor);
        btnRegister.setForeground(ColorScheme.quaternaryColor);
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLoginAcct;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JLabel lblRetypePwd;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRetypePwd;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
